src/Entity/Configuration.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Doctrine\Behavior\TimestampableEntity;
use App\Enum\ConfigurationType;
use App\Message\Command\Admin\ParametersFormCommand;
use App\Repository\ConfigurationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ConfigurationRepository::class)]
class Configuration
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(name: 'type', type: 'string', nullable: false, enumType: ConfigurationType::class)]
    #[Assert\NotBlank]
    protected ConfigurationType $type = ConfigurationType::INSTANCE;

    /**
     * @var Collection<int, PlatformOffer>
     */
    #[ORM\OneToMany(mappedBy: 'configuration', targetEntity: PlatformOffer::class, orphanRemoval: true)]
    #[ORM\OrderBy(['price' => 'ASC'])]
    private Collection $offers;

    /**
     * Associative array to store parameters.
     *
     * @var array<string, array<string,mixed>>
     */
    #[ORM\Column(type: 'json')]
    private array $configuration = [];

    public function __construct()
    {
        $this->offers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ConfigurationType
    {
        return $this->type;
    }

    public function setType(ConfigurationType $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return array<string, array<string,mixed>>
     */
    public function getConfiguration(): array
    {
        return $this->configuration;
    }

    /**
     * @param array<string, array<string,mixed>> $configuration
     */
    public function setConfiguration(array $configuration): self
    {
        $this->configuration = $configuration;

        return $this;
    }

    public static function getInstanceConfiguration(): Configuration
    {
        return (new self())->setType(ConfigurationType::INSTANCE);
    }

    /** end of basic getters and setters ------------------------------------------------ */

    /**
     * @return array<string, bool|string>
     */
    public function getGlobals(): array
    {
        /** @var array<string, bool|string> $globals */
        $globals = $this->configuration['global'] ?? [];

        return $globals;
    }

    public function getPlatformName(): string
    {
        $globals = $this->getGlobals();

        return (string) ($globals['globalName'] ?? '');
    }

    public function getServicesEnabled(): bool
    {
        $globals = $this->getGlobals();

        return (bool) $globals['globalServicesEnabled'];
    }

    public function getPaidMembership(): bool
    {
        $globals = $this->getGlobals();

        return (bool) $globals['globalPaidMembership'];
    }

    /**
     * @return array<string, string>
     */
    public function getNotificationsSender(): array
    {
        /** @var array<string, string> $notificationsSender */
        $notificationsSender = $this->configuration['notificationsSender'] ?? [];

        return $notificationsSender;
    }

    public function getNotificationsSenderEmail(): string
    {
        $notificationsSender = $this->getNotificationsSender();

        return $notificationsSender['notificationsSenderEmail'] ?? '';
    }

    public function getNotificationsSenderName(): string
    {
        $notificationsSender = $this->getNotificationsSender();

        return $notificationsSender['notificationsSenderName'] ?? '';
    }

    /**
     * @return array<mixed>
     */
    public function getContactInformations(): array
    {
        /** @var array<mixed> $contactInfo */
        $contactInfo = $this->configuration['contact'] ?? [];

        return $contactInfo;
    }

    public function getContactEnabled(): bool
    {
        /** @var array<bool> $contactEnabled */
        $contactEnabled = $this->getContactInformations();

        return $contactEnabled['contactFormEnabled'];
    }

    public function getContactEmail(): string
    {
        /** @var array<string> $contactEnabled
         */
        $contactEnabled = $this->getContactInformations();

        return $contactEnabled['contactFormEmail'];
    }

    public function isConversationAdminAccessible(): bool
    {
        /** @var array<bool> $config */
        $config = $this->configuration['confidentiality'] ?? [];

        return $config['confidentialityConversationAdminAccess'];
    }

    public function isGroupsCreationForAll(): bool
    {
        return $this->configuration['groups']['groupsCreationMode'] === ParametersFormCommand::ALL;
    }

    // for test only
    public function setGroupsCreationModeToAdminOnly(): self
    {
        $this->configuration['groups']['groupsCreationMode'] = ParametersFormCommand::ONLY_ADMIN;

        return $this;
    }
}

src/EasyAdmin/Form/Type/GroupType.php
<?php

declare(strict_types=1);

namespace App\EasyAdmin\Form\Type;

use App\Controller\Admin\DashboardController;
use App\Entity\Group;
use App\Entity\User;
use App\Repository\GroupRepository;
use App\Security\Checker\AuthorizationChecker;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Form type for filtering on a group relation.
 */
class GroupType extends AbstractType
{
    public function __construct(
        private readonly Security $security,
        private readonly AuthorizationChecker $authorizationChecker,
    ) {
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'class' => Group::class,
            'className' => Group::class,
            'translation_domain' => DashboardController::DOMAIN,
        ]);

        // restrict to allowed groups only
        if (!$this->authorizationChecker->isAdmin()) {
            /** @var User $user */
            $user = $this->security->getUser();
            $resolver->setDefault('query_builder', function (GroupRepository $repo) use ($user) {
                return $repo->createQueryBuilder('entity')
                    ->andWhere('entity.id IN (:groups)')
                    ->setParameter(':groups', $user->getMyGroupsAsAdmin());
            });
        }
    }

    public function getParent(): string
    {
        return EntityType::class;
    }
}

src/Controller/Group/CreateGroupAction.php
<?php

declare(strict_types=1);

namespace App\Controller\Group;

use App\Controller\Admin\GroupCrudController;
use App\Controller\FlashTrait;
use App\Controller\i18nTrait;
use App\Controller\RequestTrait;
use App\Controller\User\MyAccountAction;
use App\Entity\Group;
use App\Entity\User;
use App\Entity\UserGroup;
use App\Form\Type\Group\CreateGroupFormType;
use App\MessageBus\QueryBus;
use App\Repository\ConfigurationRepository;
use App\Repository\GroupRepository;
use App\Repository\UserGroupRepository;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use Symfony\Component\Security\Http\Attribute\IsGranted;

/**
 * @see CreateGroupActionTest
 */
#[Route(name: 'app_group_')]
final class CreateGroupAction extends AbstractController
{
    use RequestTrait;
    use i18nTrait;
    use FlashTrait;
    use GroupTrait;

    public function __construct(
        private readonly QueryBus $queryBus,
        private readonly GroupRepository $groupRepository,
        private readonly ConfigurationRepository $configurationRepository,
        private readonly UserGroupRepository $userGroupRepository,
        private readonly AdminUrlGenerator $adminUrlGenerator,
        private readonly Security $security,
        private readonly EntityManagerInterface $doctrine,
    ) {
    }

    #[IsGranted(User::ROLE_USER)]
    #[Route([
        'en' => MyAccountAction::BASE_URL_EN.'/groups/create-my-group',
        'fr' => MyAccountAction::BASE_URL_FR.'/groupes/creer-mon-groupe',
    ],
        name: 'create',
    )]
    public function createGroup(Request $request, #[CurrentUser] User $user): Response
    {
        // Admin must use the admin interface
        if ($user->isAdmin()) {
            return $this->redirect(
                $this->adminUrlGenerator
                    ->setController(GroupCrudController::class)
                    ->set('crudAction', Crud::PAGE_NEW)
                    ->generateUrl()
            );
        }

        $configuration = $this->configurationRepository->getInstanceConfigurationOrCreate();
        if (!$configuration->isGroupsCreationForAll()) {
            throw $this->createAccessDeniedException('Cannot create group with current settings.');
        }

        $newGroup = (new Group())->setInvitationByAdmin(true);
        $form = $this->createForm(CreateGroupFormType::class, $newGroup)->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->groupRepository->save($newGroup, true);
            $newAdminGroup = UserGroup::newUserGroup($user, $newGroup);
            $this->userGroupRepository->save($newAdminGroup, true);

            // force login to refresh the roles so the user can access its group
            // in the group admin interface
            $this->doctrine->refresh($user);
            $this->security->login($user);

            return $this->redirect(
                $this->adminUrlGenerator
                    ->setController(GroupCrudController::class)
                    ->setEntityId($newGroup->getId())
                    ->set('crudAction', Crud::PAGE_EDIT)
                    ->generateUrl()
            );
        }

        return $this->render('pages/group/create.html.twig', compact('form'));
    }
}

src/Controller/Group/GroupController.php
<?php

declare(strict_types=1);

namespace App\Controller\Group;

use App\Controller\FlashTrait;
use App\Controller\i18nTrait;
use App\Controller\RequestTrait;
use App\Doctrine\Manager\ProductManager;
use App\Entity\Group;
use App\Entity\User;
use App\Form\Type\Product\GroupSelectFormType;
use App\Message\Query\Group\GetGroupMembersQuery;
use App\Message\Query\Group\GetGroupsQuery;
use App\MessageBus\QueryBus;
use Doctrine\ORM\Query;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Uid\Uuid;

/**
 * @see GroupControllerTest
 */
#[Route(name: 'app_group_')]
final class GroupController extends AbstractController
{
    use RequestTrait;
    use i18nTrait;
    use FlashTrait;
    use GroupTrait;

    public const MAX_ELEMENT_BY_PAGE = 20;

    public function __construct(
        private readonly QueryBus $queryBus,
        private readonly PaginatorInterface $paginator,
        private readonly ProductManager $productManager,
    ) {
    }

    #[Route([
        'en' => '/{_locale}/groups',
        'fr' => '/{_locale}/groupes',
    ],
        name: 'list'
    )]
    public function list(Request $request, #[CurrentUser] ?User $user): Response
    {
        $page = $this->getPage($request);
        $form = $this->createForm(GroupSelectFormType::class)->handleRequest($request);
        $groupName = null;
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var string $groupName */
            $groupName = $form->get('q')->getData();
        }

        /** @var Query $query */
        $query = $this->queryBus->query(new GetGroupsQuery($user, $groupName));
        $pagination = $this->paginator->paginate($query, $page, self::MAX_ELEMENT_BY_PAGE);

        return $this->render('pages/group/list.html.twig', compact('pagination', 'form'));
    }

    /**
     * The slug is only for SEO.
     */
    #[Route([
        'en' => '/{_locale}/groups/{slug}/{id}',
        'fr' => '/{_locale}/groupes/{slug}/{id}',
    ],
        name: 'show',
        requirements: ['slug' => Requirement::ASCII_SLUG, 'id' => Requirement::UUID_V6]
    )]
    public function show(string $id, #[CurrentUser] ?User $user): Response
    {
        $group = $this->getGroup($id);
        $showQuitGroupChoices = $this->getShowQuitGroupsChoices($group, $user);

        return $this->render('pages/group/show.html.twig', compact('group', 'showQuitGroupChoices'));
    }

    /**
     * This is the same route as show but it requires to be logged. It is useful to
     * redirect the user to this page if he isn't logged, so he can accept a pending
     * invitation for example.
     */
    #[IsGranted(User::ROLE_USER)]
    #[Route([
        'en' => '/en/groups/{slug}/{id}/invitation',
        'fr' => '/fr/groupes/{slug}/{id}/invitation',
    ],
        name: 'show_logged',
        requirements: ['slug' => Requirement::ASCII_SLUG, 'id' => Requirement::UUID_V6]
    )]
    public function showLogged(string $id, #[CurrentUser] ?User $user): Response
    {
        $group = $this->getGroup($id);
        $showQuitGroupChoices = $this->getShowQuitGroupsChoices($group, $user);

        return $this->render('pages/group/show.html.twig', compact('group', 'showQuitGroupChoices'));
    }

    private function getShowQuitGroupsChoices(Group $group, ?User $user): bool
    {
        return $this->productManager->hasProductsOnlyInGroup($group, $user);
    }

    #[Route([
        'en' => '/{_locale}/groups/{slug}/{id}/members',
        'fr' => '/{_locale}/groupes/{slug}/{id}/membres',
    ],
        name: 'members',
        requirements: ['slug' => Requirement::ASCII_SLUG, 'id' => Requirement::UUID_V6]
    )]
    public function showMembers(Request $request, string $id): Response
    {
        $group = $this->getGroup($id);
        $page = $this->getPage($request);
        $form = $this->createForm(GroupSelectFormType::class)->handleRequest($request);

        $memberName = null;
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var string $memberName */
            $memberName = $form->get('q')->getData();
        }

        /** @var Query $query */
        $query = $this->queryBus->query(new GetGroupMembersQuery(Uuid::fromString($id), $memberName));
        $pagination = $this->paginator->paginate($query, $page, self::MAX_ELEMENT_BY_PAGE);

        return $this->render('pages/group/members.html.twig', compact('pagination', 'form', 'group'));
    }
}

src/Controller/Group/GroupTrait.php
<?php

declare(strict_types=1);

namespace App\Controller\Group;

use App\Entity\Group;
use App\Message\Query\Group\GetGroupByIdQuery;
use Symfony\Component\Messenger\Exception\HandlerFailedException;
use Symfony\Component\Uid\Uuid;

trait GroupTrait
{
    private function getGroup(string $id): Group
    {
        try {
            /** @var Group $group */
            $group = $this->queryBus->query(new GetGroupByIdQuery(Uuid::fromString($id)));
        } catch (HandlerFailedException $e) {
            throw $this->createNotFoundException($e->getMessage());
        }

        return $group;
    }
}

src/Controller/Payment/Group/GroupOfferTrait.php
<?php

declare(strict_types=1);

namespace App\Controller\Payment\Group;

use App\Entity\GroupOffer;
use App\Repository\GroupOfferRepository;
use Symfony\Component\Uid\Uuid;

/**
 * @property GroupOfferRepository $groupOfferRepository
 */
trait GroupOfferTrait
{
    public function getGroupOffer(string $id): GroupOffer
    {
        $groupOffer = $this->groupOfferRepository->find(Uuid::fromString($id));
        if ($groupOffer === null || !$groupOffer->isActive()) {
            throw $this->createNotFoundException('Group offer not found');
        }

        return $groupOffer;
    }
}

templates/pages/group/create.html.twig
{% extends 'layout/base.html.twig' %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% set i18n_prefix = _self|i18n_prefix %}


{% block body %}
    <div class="px-3 px-lg-0">
        {% include 'components/layout/_title_3.html.twig' with {
            rowClass: 'mt-4',
            name: (i18n_prefix ~ '.title')|trans
        } %}
        <div class="row mt-3 justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-5">
                {{ form_start(form) }}
                    {{ form_row(form.name) }}
                    {{ form_row(form.type) }}
                    {{ form_row(form.membership) }}

                    <div {{ stimulus_controller('parentgroup') }}>
                        {% if form.servicesEnabled is defined %}
                            <div
                                {{ stimulus_target('parentgroup', 'servicesField') }}
                                data-product-route-value="{{ path('app_group_list') }}"
                            >
                                {{ form_widget(form.servicesEnabled) }}
                            </div>
                        {% endif %}
                        {% if form.parent is defined and form.parent is not null %}
                            {{ form_row(form.parent) }}
                        {% endif %}
                    </div>
                    {{ form_widget(form.submit) }}
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block link %}{% endblock %}

templates/pages/group/list.html.twig
{% extends 'layout/base.html.twig' %}

{% set i18n_prefix = _self|i18n_prefix %}

{% block container %}container-fluid{% endblock %}

{% block body %}
    {% include 'components/layout/_title_3.html.twig' with {
        name: (i18n_prefix ~ '.title')|trans
    } %}
    <div class="px-3 px-lg-5">
        {% include 'components/layout/_searchbar.html.twig' with {
            col: 'col col-lg-5',
            placeholder: (i18n_prefix ~ '.placeholder')|trans,
        } %}
        <div class="row flex-column">
            <div class="col col-lg-5 mx-lg-auto">
                <div class="card mt-5">
                    <ul class="list-group list-group-flush">
                        {% for group in pagination %}
                            <li class="list-group-item group-test">
                                {% include 'components/group/_card.html.twig' with {
                                    group,
                                    link: path('app_group_show', {id: group.id, slug: group.slug})
                                } %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                {% include 'components/layout/_pagination.html.twig' with {pagination} %}
            </div>
        </div>
    </div>
{% endblock %}

{% block link %}{% endblock %}

templates/pages/group/members.html.twig
{% extends 'layout/base.html.twig' %}

{% set i18n_prefix = _self|i18n_prefix %}

{% block body %}
    {% include 'components/layout/_title_3.html.twig' with {
        name: (i18n_prefix ~ '.title')|trans
    } %}
    <div class="row my-4 px-3">
    {% include 'components/layout/_searchbar.html.twig' with {
        margin: 'my-3 my-lg-0 me-lg-3'
    } %}
    </div>
    <div class="my-4">
        {% if pagination is empty %}
            <p class="text-center mt-5">{{ (i18n_prefix ~ '.no_result')|trans }}</p>
        {% else %}
            {% for member in pagination %}
                {% include 'components/group/_member_card.html.twig' with {
                    user: member.user,
                    category: member.user.category,
                    isInvited: member.membership.isInvited,
                    group,
                } %}
            {% endfor %}
            {% include 'components/layout/_pagination.html.twig' with {pagination} %}
            {% if is_granted('IS_AUTHENTICATED') and app.user.isGroupAdmin(group) %}
                <div class="row justify-content-center">
                    <a
                        href="{{ ea_url().setController('App\\Controller\\Admin\\GroupCrudController').setAction('detail').setEntityId(group.id) }}"
                        class="btn btn-primary col-8 col-md-3 admin-button-test"
                    >
                        <i class="fa-solid fa-arrow-up-right-from-square"></i>
                        {{ (i18n_prefix ~ '.manage_button')|trans }}
                    </a>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

{% block link %}{% endblock %}

templates/pages/group/show.html.twig
{% extends 'layout/base.html.twig' %}

{% set i18n_prefix = _self|i18n_prefix %}

{# User logged? #}
{% set logged = is_granted('IS_AUTHENTICATED_REMEMBERED') %}

{# Is the group public? #}
{% set is_public = group.type.isPublic %}

{# Get the current status of the user for the current group #}
{% set group_membership = logged ? app.user.getGroupMembership(group) : null %}
{% set has_group_membership = group_membership != null %}

{# Can we display the show members button? #}
{% set display_show_members_button = is_public or (has_group_membership and group_membership.membership.isConfirmed) %}

{% block body %}
    <div class="px-3 px-lg-0">
        {% include 'components/layout/_title_3.html.twig' with {
            name: group.name
        } %}

        <div class="d-flex justify-content-center mt-3">
            {% set pill_bg = group.type.isPublic() ? 'text-primary text-bg-blue-custom' : 'text-bg-secondary' %}
            <span class="badge d-inline-flex align-items-center rounded-pill {{ pill_bg }}">
                {{ group.type.value|trans }}
            </span>
        </div>

        {% include 'components/layout/_text.html.twig' with {
            text: group.description
        } %}

        {# 1. logged but not member and no pending invitaton #}
        {% if logged and not has_group_membership %}
            {% include 'pages/group/show/_logged_without_link.html.twig' %}

        {# 2. logged and has a link with the group #}
        {% elseif logged and has_group_membership %}
            {% include 'pages/group/show/_logged_with_link.html.twig' %}

        {# 3. not logged, display the link to login and come back to this page #}
        {% else %}
            <p class="text-center">
                <a href="{{ path('app_group_show_logged', {id: group.id, slug: group.slug}) }}">{{ (i18n_prefix ~ '.login_text')|trans }}</a>
            </p>
        {% endif %}

        {% if display_show_members_button %}
            <div class="d-grid col col-lg-4 mx-auto mt-5">
                <a class="btn btn-outline-primary"
                   href="{{ path('app_group_members', {id: group.id, slug: group.slug}) }}">
                    <i class="bi bi-people"></i>
                    {{ (i18n_prefix ~ '.show_members')|trans }}
                </a>
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block link %}{% endblock %}