src/Entity/Product.php
<?php

declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Patch;
use App\Controller\i18nTrait;
use App\Doctrine\Behavior\TimestampableEntity;
use App\Doctrine\Listener\ProductListener;
use App\Enum\Product\ProductStatus;
use App\Enum\Product\ProductType;
use App\Enum\Product\ProductVisibility;
use App\Form\Type\Product\AbstractProductFormType;
use App\Repository\ProductRepository;
use App\Security\Voter\ProductVoter;
use App\State\Processor\ProductSwitchProcessor;
use Carbon\Carbon;
use Carbon\CarbonImmutable;
use Carbon\CarbonInterface;
use Carbon\CarbonInterval;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[ORM\Table]
#[ORM\Index(columns: ['type', 'status', 'visibility', 'owner_id'])]
#[ORM\EntityListeners([ProductListener::class])]
#[ApiResource(
    operations: [
        new Patch(
            uriTemplate: '/product/{id}/switchStatus',
            openapiContext: ['summary' => 'Switch the status of the product'],
            normalizationContext: ['groups' => [ProductSwitchProcessor::class]],
            security: "is_granted('".ProductVoter::EDIT."', object)",
            input: false,
            processor: ProductSwitchProcessor::class,
        ),
    ]
)]
class Product implements \Stringable, ImagesInterface
{
    use TimestampableEntity;
    use ProductObjectTrait;
    use ProductServiceTrait;
    use i18nTrait;

    final public const DEFAULT_CURRENCY = 'EUR';

    /**
     * Generates a V6 uuid.
     */
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    #[ApiProperty(identifier: true)]
    #[Groups([ProductSwitchProcessor::class])]
    private Uuid $id;

    /**
     * Type of the product. It can be an object to lend or a service.
     */
    #[ORM\Column(name: 'type', type: 'string', nullable: false, enumType: ProductType::class)]
    #[Assert\NotBlank]
    protected ProductType $type;

    /**
     * Main category of the product (1st or second level).
     */
    #[ORM\ManyToOne(targetEntity: Category::class)]
    #[ORM\JoinColumn(referencedColumnName: 'id', nullable: false)]
    #[Assert\NotBlank(groups: [AbstractProductFormType::class])]
    private Category $category;

    /**
     * Status of the product.
     */
    #[ORM\Column(name: 'status', type: 'string', nullable: false, enumType: ProductStatus::class)]
    #[Assert\NotBlank]
    #[Groups([ProductSwitchProcessor::class])]
    protected ProductStatus $status;

    /**
     * Visibility of the product.
     */
    #[ORM\Column(name: 'visibility', type: 'string', nullable: false, enumType: ProductVisibility::class)]
    #[Assert\NotBlank]
    protected ProductVisibility $visibility = ProductVisibility::PUBLIC;

    /**
     * User that owns the product or propose the service.
     */
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')] // if the owner is deleted then the product will also be deleted without constraint error
    #[Assert\NotBlank]
    protected User $owner;

    /**
     * Short and main name of the product.
     */
    #[ORM\Column(type: Types::STRING, length: 255, nullable: false)]
    #[Assert\NotBlank(groups: [AbstractProductFormType::class])]
    #[Assert\Length(max: 255, groups: [AbstractProductFormType::class, 'default'])]
    private string $name;

    /**
     * SEO friendly name for URLs.
     */
    #[ORM\Column(length: 255, unique: false)]
    #[Gedmo\Slug(fields: ['name'])]
    private string $slug;

    /**
     * Longer description of the product.
     */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\NotBlank(groups: [AbstractProductFormType::class])]
    #[Assert\Length(max: 2000, groups: [AbstractProductFormType::class])]
    private ?string $description = null;

    /**
     * User images for the product.
     *
     * @var array<string>
     */
    #[ORM\Column(type: 'json', nullable: true)]
    private ?array $images = null;

    /**
     * @var Collection<int, ProductAvailability> $availabilities
     */
    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductAvailability::class, cascade: ['persist', 'remove', 'detach'])]
    #[ORM\OrderBy(['startAt' => 'ASC'])]
    private Collection $availabilities;

    /**
     * @var Collection<int, ServiceRequest> $serviceRequests
     */
    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ServiceRequest::class)]
    private Collection $serviceRequests;

    /**
     * If the product in not public then the list of group the product is visible.
     *
     * @var Collection<int, Group> $groups
     */
    #[ORM\ManyToMany(targetEntity: Group::class, inversedBy: 'products')]
    #[Assert\When(
        expression: '!this.getVisibility().isPublic() && !this.getOwner().getUserGroupsConfirmedWithServices().isEmpty()',
        constraints: [
            new Assert\Count(min: 1, minMessage: 'app.entity.product.groups.constraints.count.min_message'),
        ],
        groups: [AbstractProductFormType::class],
    )]
    private Collection $groups;

    /**
     * This is a virtual field to store the distance with a given location when
     * using a proximity filter.
     */
    private ?int $geoDistance = null;

    /**
     * Get distance in meters.
     */
    public function setGeoDistance(?int $geoDistance): self
    {
        $this->geoDistance = $geoDistance;

        return $this;
    }

    /**
     * Return kilometers.
     */
    public function getGeoDistance(): ?float
    {
        return $this->geoDistance !== null ? $this->geoDistance / 1000 : null;
    }

    public function __construct()
    {
        $this->availabilities = new ArrayCollection();
        $this->serviceRequests = new ArrayCollection();
        $this->groups = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $uuid): self
    {
        $this->id = $uuid;

        return $this;
    }

    public function getType(): ProductType
    {
        return $this->type;
    }

    public function setType(ProductType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCategory(): Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStatus(): ProductStatus
    {
        return $this->status;
    }

    public function setStatus(ProductStatus $status): Product
    {
        $this->status = $status;

        return $this;
    }

    public function getVisibility(): ProductVisibility
    {
        return $this->visibility;
    }

    public function setVisibility(ProductVisibility $visibility): self
    {
        $this->visibility = $visibility;

        return $this;
    }

    public function getOwner(): User
    {
        return $this->owner;
    }

    public function isOwner(User $user): bool
    {
        return $this->owner === $user;
    }

    public function setOwner(User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSlug(): string
    {
        return $this->slug;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImages(): ?array
    {
        return $this->images;
    }

    public function getFirstImage(): ?string
    {
        return $this->images[0] ?? null;
    }

    /**
     * @param array<string|null>|null $images
     */
    public function setImages(?array $images): self
    {
        $this->images = array_values(array_filter($images ?? [])); // make sure we don't save null or empty values

        return $this;
    }

    /**
     * @param array<string> $images
     */
    public function addImages(array $images): self
    {
        $this->images = array_merge($this->images ?? [], $images);

        return $this;
    }

    /**
     * @return Collection<int, ProductAvailability>
     */
    public function getAvailabilities(): Collection
    {
        return $this->availabilities;
    }

    /**
     * @param Collection<int, ProductAvailability> $availabilities
     */
    public function setAvailabilities(Collection $availabilities): self
    {
        $this->availabilities = $availabilities;

        return $this;
    }

    public function addAvailability(ProductAvailability $productAvailability): self
    {
        if (!$this->availabilities->contains($productAvailability)) {
            $this->availabilities->add($productAvailability);
            $productAvailability->setProduct($this);
        }

        return $this;
    }

    public function removeAvailability(ProductAvailability $productAvailability): self
    {
        $this->availabilities->removeElement($productAvailability);

        return $this;
    }

    /**

templates/components/item/_conversation.html.twig
<a href="{{ path('app_user_conversation_list', {'id': id}) }}" title="{{ 'conversations.list.link'|trans }}"
   class="conversations-link d-block m-0 px-3">
    <div class="row m-0 py-3 border-bottom">
        <div class="col-auto p-0">
            {% if product.images is not empty %}
                <img src="{{ product|public_url_image(product.firstImage) }}" alt="{{ product_name }}" class="featured-image"
                     width="100">
            {% elseif product.category.image is not empty %}
                <img src="{{ product.category|public_url }}" alt="{{ product_name }}" class="featured-image"
                     width="100">
            {% else %}
                <img src="{{ asset('svg/product.svg') }}" alt="{{ product_name }}" class="featured-image"
                     width="100">
            {% endif %}
        </div>
        <div class="col">
            <h6 class="fw-bold m-0">{{ name }}</h6>
            <p class="fs-7 m-0">{{ product_name }} - {{ date|date('d/m/Y') }}</p>
            <div class="mt-2">
                {% include 'components/conversation/_badge.html.twig' with {
                    status
                } %}
            </div>
        </div>
        <div class="col-auto align-self-center p-0">
            <div class="position-relative">
                <i class="fa-solid fa-message"></i>
                {% if has_message %}
                    <span class="position-absolute top-0 start-100 translate-middle p-1 rounded-circle bg-danger">
                        <span class="visually-hidden">{{ 'conversations.list.new_messages'|trans }}</span>
                    </span>
                {% endif %}
            </div>
        </div>
        <div class="col-auto align-self-center">
            <i class="fa-solid fa-chevron-right"></i>
        </div>
    </div>
</a>

templates/components/item/_product.html.twig
{% set i18n_prefix = _self|i18n_prefix %}

<div
    class="d-block m-0"
    data-controller="product"
    data-product-id-value="{{ product.id }}"
    data-product-route-value="{{ path('_api_/product/{id}/switchStatus_patch', {id: product.id}) }}"
    data-test-product
>
    <div class="row m-0 py-3 border-bottom">
        <div class="col-auto p-0 align-self-center">
            <a href="#">
                {% if product.images is not empty %}
                    <img src="{{ product|public_url_image(product.firstImage) }}" alt="{{ product.name }}" class="featured-image" width="74" height="74">
                {% elseif category.image %}
                    <img src="{{ category|public_url }}" alt="{{ product.name }}" class="featured-image" width="74" height="74">
                {% else %}
                    <img src="{{ asset('svg/product.svg') }}" alt="{{ product.name }}" class="featured-image" width="74" height="74">
                {% endif %}
            </a>
        </div>
        <div class="col align-self-center">
            <h6 class="fw-bold m-0">
                <a href="{{ path('app_product_show', {slug: product.slug, id: product.id}) }}">{{ product.name }}</a>
            </h6>
            <p class="fs-7 m-0">
                {% if category.parent %}
                    {{ category.parent }} &nbsp;/&nbsp;
                {% endif %}
                {{ category }}
            </p>
            <div
                class="mt-2 {% if product.isPaused() %}d-none{% endif %}"
                data-product-target="activeTag"
            >
                {% include 'components/utils/_badge.html.twig' with {
                    type: 'success',
                    name: (i18n_prefix ~ '.active')|trans
                } %}
            </div>
            <div
                class="mt-2 {% if product.isActive() %}d-none{% endif %}"
                data-product-target="pausedTag"
            >
                {% include 'components/utils/_badge.html.twig' with {
                    type: 'secondary',
                    name: (i18n_prefix ~ '.paused')|trans
                } %}
            </div>
        </div>
        <div class="col-auto align-self-center">
            {% if has_conversation %}
                <a href="{{ path('app_user_my_lendings', {'user_lending_product_select_form[product]': [product.id]}) }}" class="position-relative text-black">
                    <i class="bi bi-chat-left-text-fill"></i>
                </a>
            {% endif %}
        </div>
        <div class="col-auto align-self-center">
            <div class="dropdown">
                <button type="button" class="btn" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-three-dots-vertical"></i>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <a
                            href="{{ path(route == 'app_user_objects' ? 'app_object_edit' : 'app_service_edit', {id: product.id}) }}"
                            class="btn text-black fw-semibold text-start"
                        >
                            <i class="bi bi-pencil-fill me-2"></i> {{ (i18n_prefix ~ '.edit')|trans }}
                        </a>
                    </li>
                    <li>
                        <a
                            href="{{ path('app_user_product_duplicate', {id: product.id}) }}"
                            class="btn text-black fw-semibold text-start"
                        >
                            <i class="bi bi-clipboard-fill me-2"></i> {{ (i18n_prefix ~ '.duplicate')|trans }}
                        </a>
                    </li>
                    <li>
                        <a
                            href="{{ path('app_user_product_availabilities', {id: product.id}) }}"
                            class="btn text-black fw-semibold text-start">
                            <i class="bi bi-calendar-fill me-2"></i> {{ (i18n_prefix ~ '.manage_availabilities')|trans }}
                        </a>
                    </li>
                    <li>
                        <button
                            class="btn text-black fw-semibold text-start"
                            data-action="click->product#switchStatus"
                        >
                            <span
                                class="{% if product.isPaused() %}d-none{% endif %}"
                                data-product-target="activeButton"
                            >
                                <i class="bi bi-pause-circle-fill me-2"></i>
                                {{ (i18n_prefix ~ '.pause')|trans }}
                            </span>
                            <span
                                class="{% if product.isActive() %}d-none{% endif %}"
                                data-product-target="pausedButton"
                            >
                                <i class="bi bi-play-circle-fill me-2"></i>
                                {{ (i18n_prefix ~ '.resume')|trans }}
                            </span>
                        </button>
                    </li>
                    <li>
                        {% if not product.hasOngoingServiceRequests() %}
                            <a
                                href="{{ path('app_user_product_delete', {id: product.id}) }}"
                                class="btn text-black fw-semibold text-start"
                            >
                                <i class="bi bi-trash3-fill me-2"></i> {{ (i18n_prefix ~ '.delete')|trans }}
                            </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>