src/Entity/MenuItem.php
<?php

declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Metadata\ApiProperty;
use App\Enum\Menu\LinkType;
use App\Enum\SocialMediaType;
use App\Repository\MenuItemRepository;
use App\Validator as AppAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MenuItemRepository::class)]
#[ORM\Table]
#[AppAssert\Constraints\MenuItem\MenuItemParentNotSelf]
class MenuItem implements \Stringable
{
    /**
     * Ordering starts at 0 not 1.
     */
    final public const POSITION_FIRST = 0;

    /** Generate a V6 uuid */
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: UuidGenerator::class)]
    #[ApiProperty(identifier: true)]
    private Uuid $id;

    /**
     * Name of menu item.
     */
    #[ORM\Column(type: Types::STRING, length: 255, nullable: true)]
    #[Assert\When(
        expression: 'this.isLink()',
        constraints: [
            new Assert\NotBlank(message: 'menu.validator.field'),
        ],
    )]
    private ?string $name = null;

    /**
     * Define if the item is a link of a social network or not.
     */
    #[ORM\Column(name: 'linkType', type: 'string', enumType: LinkType::class)]
    private LinkType $linkType = LinkType::LINK;

    /**
     * Type of social media.
     */
    #[ORM\Column(name: 'mediaType', type: 'string', nullable: true, enumType: SocialMediaType::class)]
    #[Assert\When(
        expression: 'this.isSocialNetwork()',
        constraints: [
            new Assert\NotBlank(message: 'menu.validator.field'),
        ],
    )]
    private ?SocialMediaType $mediaType = null;

    /**
     * Link of the menu item.
     */
    #[ORM\Column(type: Types::STRING, length: 255)]
    private string $link;

    /**
     * Optional parent for menu item.
     */
    #[Gedmo\SortableGroup]
    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'children')]
    private ?self $parent = null;

    /**
     * @var Collection<int, self> $children
     */
    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: self::class)]
    #[ORM\OrderBy(['position' => 'ASC'])]
    private Collection $children;

    /**
     * Menu related to items.
     */
    #[Gedmo\SortableGroup]
    #[ORM\ManyToOne(targetEntity: Menu::class, inversedBy: 'items')]
    private Menu $menu;

    /**
     * Position of the item in the front menu.
     */
    #[Gedmo\SortablePosition]
    #[ORM\Column(name: 'position', type: 'integer')]
    private int $position;

    public function __construct()
    {
        $this->children = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->name ?? $this->link;
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $uuid): self
    {
        $this->id = $uuid;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLinkType(): LinkType
    {
        return $this->linkType;
    }

    public function setLinkType(LinkType $linkType): void
    {
        $this->linkType = $linkType;
    }

    public function getMediaType(): ?SocialMediaType
    {
        return $this->mediaType;
    }

    public function setMediaType(?SocialMediaType $mediaType): void
    {
        $this->mediaType = $mediaType;
    }

    public function getLink(): string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function hasChildren(): bool
    {
        return !$this->children->isEmpty();
    }

    /**
     * @param Collection<int, self> $children
     */
    public function setChildren(Collection $children): self
    {
        $this->children = $children;

        return $this;
    }

    public function getMenu(): Menu
    {
        return $this->menu;
    }

    public function setMenu(Menu $menu): MenuItem
    {
        $this->menu = $menu;

        return $this;
    }

    public function getPosition(): int
    {
        return $this->position;
    }

    public function setPosition(int $position): void
    {
        $this->position = $position;
    }

    public function getPositionHuman(): int
    {
        return $this->position + 1;
    }

    public function isFirst(): bool
    {
        return $this->position === self::POSITION_FIRST;
    }

    public function up(): int
    {
        return $this->position - 1;
    }

    public function down(): int
    {
        return $this->position + 1;
    }

    public function isLink(): bool
    {
        return $this->linkType === LinkType::LINK;
    }

    public function isSocialNetwork(): bool
    {
        return $this->linkType === LinkType::SOCIAL_NETWORK;
    }
}

src/EasyAdmin/Form/Type/UserType.php
<?php

declare(strict_types=1);

namespace App\EasyAdmin\Form\Type;

use App\Controller\Admin\DashboardController;
use App\Entity\User;
use App\Repository\UserRepository;
use App\Security\Checker\AuthorizationChecker;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Form type for filtering users on selected groups.
 */
class UserType extends AbstractType
{
    public function __construct(
        private readonly Security $security,
        private readonly AuthorizationChecker $authorizationChecker,
    ) {
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'class' => User::class,
            'className' => User::class,
            'translation_domain' => DashboardController::DOMAIN,
        ]);

        // restrict to allowed groups only
        if (!$this->authorizationChecker->isAdmin()) {
            /** @var User $user */
            $user = $this->security->getUser();

            $resolver->setDefault('query_builder', function (UserRepository $repo) use ($user) {
                return $repo->createQueryBuilder('entity')
                    ->innerJoin('entity.userGroups', 'ug')
                    ->andWhere('ug.group IN (:groups)')
                    ->setParameter(':groups', $user->getMyGroupsAsAdmin());
            });
        }
    }

    public function getParent(): string
    {
        return EntityType::class;
    }
}

src/Controller/User/Account/ChangeLoginAction.php
<?php

declare(strict_types=1);

namespace App\Controller\User\Account;

use App\Controller\FlashTrait;
use App\Controller\i18nTrait;
use App\Controller\SecurityTrait;
use App\Controller\User\MyAccountAction;
use App\Entity\User;
use App\Form\Type\User\ChangeLoginFormType;
use App\Message\Command\User\ChangeLoginCommand;
use App\MessageBus\CommandBus;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use Symfony\Component\Security\Http\Attribute\IsGranted;

/**
 * @see ChangeLoginActionTest
 */
final class ChangeLoginAction extends AbstractController
{
    use SecurityTrait;
    use FlashTrait;
    use i18nTrait;

    public function __construct(
        private readonly CommandBus $commandBus,
        private readonly EntityManagerInterface $entityManager,
    ) {
    }

    #[IsGranted(AuthenticatedVoter::IS_AUTHENTICATED_FULLY)]
    #[Route(path: [
        'en' => MyAccountAction::BASE_URL_EN.'/my-email',
        'fr' => MyAccountAction::BASE_URL_FR.'/mon-email',
    ], name: 'app_user_change_login')]
    public function __invoke(Request $request, #[CurrentUser] User $user): Response
    {
        $form = $this->createForm(ChangeLoginFormType::class, $user)->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->addFlashSuccess($this->getI18nPrefix().'.flash.success');
            /** @var string $email */
            $email = $form->get('email')->getData();
            $command = new ChangeLoginCommand($user->getId(), $email);
            $this->commandBus->dispatch($command);

            return $this->redirectToRoute(MyAccountAction::ROUTE);
        }

        // In case of error, we must reload the original email
        $this->entityManager->refresh($user);

        return $this->render('pages/user/account/change_login.html.twig', compact('form'));
    }
}

src/Controller/User/Account/ChangePasswordAction.php
<?php

declare(strict_types=1);

namespace App\Controller\User\Account;

use App\Controller\FlashTrait;
use App\Controller\i18nTrait;
use App\Controller\User\MyAccountAction;
use App\Doctrine\Manager\UserManager;
use App\Entity\User;
use App\Form\Type\User\ChangePasswordFormType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class ChangePasswordAction extends AbstractController
{
    use i18nTrait;
    use FlashTrait;

    public function __construct(
        private readonly UserRepository $userRepository,
        private readonly UserManager $userManager,
    ) {
    }

    #[IsGranted(AuthenticatedVoter::IS_AUTHENTICATED_FULLY)]
    #[Route(path: [
        'en' => MyAccountAction::BASE_URL_EN.'/my-password',
        'fr' => MyAccountAction::BASE_URL_FR.'/mon-mot-de-passe',
    ], name: 'app_user_change_password')]
    public function __invoke(Request $request, #[CurrentUser] User $user): Response
    {
        $form = $this->createForm(ChangePasswordFormType::class)->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var string $plaintextPassword */
            $plaintextPassword = $form->get('plainPassword')->getData();

            $this->userManager->updatePassword($user->setPlainPassword($plaintextPassword));
            $this->userRepository->save($user, true);

            $this->addFlashSuccess($this->getI18nPrefix().'.flash.success');

            return $this->redirectToRoute('app_user_my_account');
        }

        return $this->render('pages/user/account/change_password.html.twig', compact('form'));
    }
}

src/Controller/User/Account/DeleteUserAvatarAction.php
<?php

declare(strict_types=1);

namespace App\Controller\User\Account;

use App\Controller\FlashTrait;
use App\Controller\i18nTrait;
use App\Controller\User\MyAccountAction;
use App\Doctrine\Manager\UserManager;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use Symfony\Component\Security\Http\Attribute\IsGranted;

/**
 * @see DeleteUserAvatarActionTest
 */
#[IsGranted(User::ROLE_USER)]
final class DeleteUserAvatarAction extends AbstractController
{
    use FlashTrait;
    use i18nTrait;

    public function __construct(
        private readonly UserManager $userManager,
    ) {
    }

    #[Route(
        path: MyAccountAction::BASE_URL_EN.'/user/{userId}/delete-avatar',
        name: 'app_user_delete_avatar',
        requirements: [
            'userId' => Requirement::UUID_V6,
        ]
    )]
    public function __invoke(#[CurrentUser] User $user): Response
    {
        $this->userManager->deleteAvatar($user);
        $this->addFlashSuccess($this->getI18nPrefix().'.flash.success');

        return $this->redirectToRoute('app_user_edit_profile');
    }
}

src/Controller/User/Account/EditProfileAction.php
<?php

declare(strict_types=1);

namespace App\Controller\User\Account;

use App\Controller\FlashTrait;
use App\Controller\i18nTrait;
use App\Controller\User\MyAccountAction;
use App\Doctrine\Manager\UserManager;
use App\Entity\User;
use App\Form\Type\User\EditProfileFormType;
use App\Repository\UserRepository;
use App\Tests\Functional\Controller\User\Account\EditProfileActionTest;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use Symfony\Component\Security\Http\Attribute\IsGranted;

/**
 * @see EditProfileActionTest
 */
final class EditProfileAction extends AbstractController
{
    use FlashTrait;
    use i18nTrait;

    public function __construct(
        private readonly UserRepository $userRepository,
        private readonly UserManager $userManager,
        private readonly EntityManagerInterface $entityManager,
    ) {
    }

    #[IsGranted(AuthenticatedVoter::IS_AUTHENTICATED_FULLY)]
    #[Route(path: [
        'en' => MyAccountAction::BASE_URL_EN.'/edit',
        'fr' => MyAccountAction::BASE_URL_FR.'/editer',
    ], name: 'app_user_edit_profile')]
    public function __invoke(Request $request, #[CurrentUser] User $user): Response
    {
        $form = $this->createForm(EditProfileFormType::class, $user)->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile|null $avatar */
            $avatar = $form->get('avatar')->getData();
            $this->userManager->upload($avatar, $user);
            $this->userRepository->save($user, true);
            $this->addFlashSuccess($this->getI18nPrefix().'.flash.success');

            return $this->redirectToRoute(MyAccountAction::ROUTE);
        }

        // In case of error, we must reload the original firstname (to display it in navbar)
        $this->entityManager->refresh($user);

        return $this->render('pages/user/account/edit_profile.html.twig', compact('form'));
    }
}

src/Controller/User/Account/ProfileAction.php
<?php

declare(strict_types=1);

namespace App\Controller\User\Account;

use App\Controller\PaginationTrait;
use App\Controller\RequestTrait;
use App\Dto\Product\Search;
use App\Entity\User;
use App\Message\Query\User\Account\GetUserQuery;
use App\MessageBus\QueryBus;
use App\Repository\ConfigurationRepository;
use App\Search\Meilisearch;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\Exception\HandlerFailedException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use Symfony\Component\Uid\Uuid;

/**
 * @see ProfileActionTest
 */
final class ProfileAction extends AbstractController
{
    use PaginationTrait;
    use RequestTrait;

    public function __construct(
        private readonly QueryBus $queryBus,
        private readonly PaginatorInterface $paginator,
        private readonly Meilisearch $meilisearch,
        private readonly ConfigurationRepository $configurationRepository,
    ) {
    }

    #[Route([
        'en' => '/{_locale}/user/{userId}',
        'fr' => '/{_locale}/utilisateur/{userId}',
    ],
        name: 'app_user_profile',
        requirements: ['slug' => Requirement::ASCII_SLUG, 'id' => Requirement::UUID_V6, 'userId' => Requirement::UUID_V6]
    )]
    public function __invoke(Request $request, string $userId, #[CurrentUser] ?User $currentUser): Response
    {
        try {
            /** @var User $user */
            $user = $this->queryBus->query(new GetUserQuery(Uuid::fromString($userId)));
        } catch (HandlerFailedException $e) {
            throw $this->createNotFoundException($e->getMessage());
        }

        $searchDto = new Search('', $this->getPage($request), $currentUser);
        $searchDto->place = $user;

        return $this->render('pages/user/account/profile.html.twig', [
            'user' => $user,
            'objects_pagination' => $this->paginate($this->meilisearch->searchObjects($searchDto)),
            'services_pagination' => $this->paginate($this->meilisearch->searchServices($searchDto)),
            'services_enabled' => $this->configurationRepository->getServicesParameter(),
        ]);
    }
}

templates/pages/user/account/change_login.html.twig
{% extends 'layout/base.html.twig' %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% block body %}
    <div class="px-3 px-lg-0">
        {% include 'components/layout/_title_3.html.twig' with {
            name: 'change_login.action.title'|trans
        } %}

        <div class="row mt-3 justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-5">
                {{ form_start(form, {
                    attr: {
                        novalidate: true,
                    }
                }) }}
                {{ form_row(form.email.first) }}
                {{ form_row(form.email.second) }}
                <div class="d-grid col-12 mt-4">
                    {{ form_widget(form.submit) }}
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block link %}{% endblock %}

templates/pages/user/account/change_password.html.twig
{% extends 'layout/base.html.twig' %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% set i18n_prefix = _self|i18n_prefix %}


{% block body %}
    <div class="px-3 px-lg-0">
        {% include 'components/layout/_title_3.html.twig' with {
            name: (i18n_prefix ~ '.title')|trans
        } %}

        <div class="row mt-3 justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-5">
                {{ form_start(form, {
                    attr: {
                        novalidate: true,
                    }
                }) }}
                {{ form_row(form.oldPassword) }}
                {% include 'components/form/_password_visibility.html.twig' with {
                    form: form.plainPassword.first
                } %}
                {% include 'components/form/_password_visibility.html.twig' with {
                    form: form.plainPassword.second
                } %}
                <div class="d-grid col-12 mt-4">
                    {{ form_widget(form.submit) }}
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block link %}{% endblock %}

templates/pages/user/account/edit_profile.html.twig
{% extends 'layout/base.html.twig' %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% set i18n_prefix = _self|i18n_prefix %}

{% block error %}{% endblock %}

{% block body %}
    <div class="px-3 px-lg-0">
        {% include 'components/layout/_title_3.html.twig' with {
            name: (i18n_prefix ~ '.title')|trans
        } %}
        <div class="row mt-3 justify-content-center">
        <div class="col-md-8 col-lg-6 col-xl-5">
            {{ form_start(form, {
                attr: {
                    novalidate: true,
                }
            }) }}
            {% if form.firstname is defined %}
                {{ form_row(form.firstname) }}
            {% endif %}

            {% if form.lastname is defined %}
                {{ form_row(form.lastname) }}
            {% endif %}

            {# place field #}
            {% if form.name is defined %}
                {{ form_row(form.name) }}
            {% endif %}

            {{ form_row(form.avatar) }}
            {% if app.user.avatar is not null %}
                {% include 'components/form/_photo_preview.html.twig' with {
                    image: app.user.avatar,
                    entity: app.user,
                    isUser: true,
                } %}
            {% endif %}

            {# place field #}
            {% if form.schedule is defined %}
                {{ form_row(form.schedule) }}
            {% endif %}

            {% if form.category is defined %}
                {{ form_row(form.category) }}
            {% endif %}

            {% if form.description is defined %}
                {{ form_row(form.description) }}
            {% endif %}

            {{ form_row(form.phone) }}

            <div class="form-switch">
                {{ form_widget(form.smsNotifications) }}
            </div>

            <div class="d-grid col-12 mt-4">
                {{ form_widget(form.submit) }}
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    </div>
{% endblock %}
{% block link %}{% endblock %}

templates/pages/user/account/profile.html.twig
{% extends 'layout/base.html.twig' %}

{% set i18n_prefix = _self|i18n_prefix %}

{% block body %}
    <div class="px-3 px-lg-0">
        <div class="d-flex justify-content-center w-100 mt-4">
            {% if user.avatar is null %}
                <img src="{{ asset('svg/product.svg') }}"
                     alt="{{ user.displayName }}"
                     width="163"
                     height="163"
                     class="img-avatar"
                >
            {% else %}
                <div class="img-avatar"
                     style="background-image: url({{ user|public_url }});
                         width: 163px;
                         height: 163px">
                </div>
            {% endif %}
        </div>

        {% include 'components/layout/_title_3.html.twig' with {
            name: user.getDisplayName,
            rowClass: 'mt-3'
        } %}

        {% if user.category is not null %}
            {% if user.category.parent is not null %}
                {% set category = user.category.parent ~ ' / ' ~ user.category %}
            {% else %}
                {% set category = user.category %}
            {% endif %}
            {% include 'components/layout/_text.html.twig' with {
                text: category,
                textAlign: 'text-center'
            } %}
        {% endif %}
        {% if user.address is not null %}
            <div class="d-flex justify-content-center mt-3">
                <span class="badge d-inline-flex align-items-center rounded-pill text-primary text-bg-blue-custom">
                    {{ user.address.subAndlocality }}
                </span>
            </div>
        {% endif %}
        {% if user.description is not null %}
            {% include 'components/layout/_text.html.twig' with {
                margin: 'mt-3',
                text: user.description,
            } %}
        {% endif %}

        {% if objects_pagination is empty and services_pagination is empty %}
            <div class="d-flex justify-content-center mt-4">
                <span>{{ (i18n_prefix ~ '.no_result')|trans }}</span>
            </div>
        {% else %}
            {% include 'components/product/_section.html.twig' with {services_enabled} %}
            {% include 'components/product/_tab_content.html.twig' with {objects_pagination, services_pagination} %}
        {% endif %}
    </div>
{% endblock %}
{% block link %}{% endblock %}